# Generated by Django 5.2.8 on 2025-11-27 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enquiry_biology_marks_enquiry_chemistry_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttransfer',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
