# Generated by Django 6.0 on 2026-01-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registration_biology_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
