# Generated by Django 6.0 on 2026-01-09 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
