# Generated by Django 6.0 on 2026-01-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_studentdocument_created_by'),
        ('core', '0013_populate_received_at'),
    ]

    operations = [
    ]
