# Generated by Django 6.0 on 2026-01-10 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_followup_data(apps, schema_editor):
    """Delete all followups before changing field type"""
    FollowUp = apps.get_model('core', 'FollowUp')
    count = FollowUp.objects.all().count()
    FollowUp.objects.all().delete()
    print(f"Deleted {count} follow-ups for migration")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_refund_model'),
    ]

    operations = [
        migrations.RunPython(clear_followup_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL),
        ),
    ]
