# Generated by Django 6.0 on 2026-01-10 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_followup_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_completion_comment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.CharField(default='', max_length=100)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.followup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
