# Generated by Django 6.0 on 2026-01-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_followupcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.followupcomment'),
        ),
        migrations.AddField(
            model_name='followupcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
