# Generated by Django 6.0 on 2026-01-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_followupcomment_parent_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_enquiry', 'Create Enquiry'), ('update_enquiry', 'Update Enquiry'), ('create_registration', 'Create Registration'), ('update_registration', 'Update Registration'), ('create_follow_up', 'Create Follow-up'), ('complete_follow_up', 'Complete Follow-up'), ('create_task', 'Create Task'), ('complete_task', 'Complete Task'), ('add_payment', 'Add Payment'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_activi_user_id_d7adda_idx'), models.Index(fields=['company_id', '-timestamp'], name='core_activi_company_2c199f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_type', models.CharField(choices=[('registration', 'Registration'), ('payment', 'Payment'), ('referral', 'Referral'), ('bonus', 'Bonus'), ('other', 'Other')], max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='core_earnin_user_id_fb9463_idx'), models.Index(fields=['company_id', '-date'], name='core_earnin_company_95926f_idx')],
            },
        ),
    ]
