# Generated by Django 6.0 on 2026-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_activitylog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='class_10_board',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='class_10_passing_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='class_10_place',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='class_10_school_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='class_10_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='class10_board',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='class10_passing_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='class10_place',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='class10_school_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='class10_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
