# Generated by Django 6.0 on 2026-01-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_enquiry_class_10_board_enquiry_class_10_passing_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
