# Generated by Django 6.0 on 2026-01-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_enquiry_caste_enquiry_religion_registration_caste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='admission_possibility',
            field=models.IntegerField(default=0, help_text='Percentage 0-100'),
        ),
        migrations.AddField(
            model_name='followup',
            name='outcome_status',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive - Admission Taken'), ('High Interest', 'High Interest'), ('Neutral', 'Neutral'), ('Low Interest', 'Low Interest'), ('Negative', 'Negative - Not Interested'), ('Follow Up Later', 'Follow Up Later')], max_length=50, null=True),
        ),
    ]
