# Generated by Django 6.0 on 2026-01-16 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_payment_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.CharField(default='', max_length=100)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='core.registration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_remarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
