# Generated by Django 6.0 on 2026-01-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_documenttransfer_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
