# Generated by Django 6.0 on 2026-01-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_physicaldocumenttransfer_courier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='company_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
