# Generated by Django 6.0 on 2026-01-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_user_assigned_district_user_assigned_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEV_ADMIN', 'Dev Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('HR', 'HR'), ('SALES', 'Sales & Marketing'), ('ACCOUNTS', 'Accounts / Finance'), ('COUNSELOR', 'Counselor'), ('OPERATIONS', 'Operations'), ('IT_SUPPORT', 'IT Support'), ('TEAM_LEADER', 'Team Leader')], default='EMPLOYEE', max_length=20),
        ),
    ]
