# Generated by Django 6.0 on 2026-01-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='encrypted_content',
            field=models.TextField(default='', help_text='Message encrypted with AES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='encrypted_keys',
            field=models.JSONField(default=dict, help_text='Format: {user_id: encrypted_aes_key}'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.JSONField(default=list, help_text='List of user IDs who have read this message'),
        ),
        migrations.AddField(
            model_name='user',
            name='rsa_private_key_encrypted',
            field=models.TextField(blank=True, help_text='RSA private key encrypted with user password', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rsa_public_key',
            field=models.TextField(blank=True, help_text='RSA public key in PEM format', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
